const products = [
  {
    id: 1,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 18.0,
    thumbnail: "https://placehold.co/600x400",
    images: [
      "https://placehold.co/600x400",
      "https://placehold.co/600x400",
      "https://placehold.co/600x400",
    ],
    category: 1,
    rating: 4.5,
    unit: "1 unit",
    description:
      "Sunstar Fresh Melon Juice is a delicious, refreshing, and nutritious juice made from fresh, locally sourced melon. This juice is packed with antioxidants, vitamins, and minerals, making it a great choice for those looking to boost their immune system and maintain a healthy lifestyle.",
  },
  {
    id: 2,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 10.0,
    thumbnail: "https://placehold.co/600x400",
    images: [],
    category: 1,
    rating: 3.5,
    unit: "1 unit",
    description:
      "Sunstar Fresh Melon Juice is a delicious, refreshing, and nutritious juice made from fresh, locally sourced melon. This juice is packed with antioxidants, vitamins, and minerals, making it a great choice for those looking to boost their immune system and maintain a healthy lifestyle.",
  },
  {
    id: 3,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 20,
    thumbnail: "https://placehold.co/600x400",
    images: [],
    category: 2,
    rating: 5,
    unit: "1 unit",
    description:
      "Sunstar Fresh Melon Juice is a delicious, refreshing, and nutritious juice made from fresh, locally sourced melon. This juice is packed with antioxidants, vitamins, and minerals, making it a great choice for those looking to boost their immune system and maintain a healthy lifestyle.",
  },
  {
    id: 4,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 18.0,
    image: "../../assets/images/thumb-bananas.png",
    category: 2,
    rating: 4.5,
    unit: "1 unit",
  },
  {
    id: 5,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 18.0,
    image: "../../assets/images/thumb-bananas.png",
    category: 3,
    rating: 4.5,
    unit: "1 unit",
  },
  {
    id: 6,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 18.0,
    image: "../../assets/images/thumb-bananas.png",
    category: 1,
    rating: 4.5,
    unit: "1 unit",
  },
  {
    id: 7,
    name: "Sunstar Fresh Melon Juice",
    discount: 30,
    price: 19,
    image: "../../assets/images/thumb-bananas.png",
    category: 3,
    rating: 4.5,
    unit: "1 unit",
  },
];

export default products;
